/**
 * Google Fit Service - Sync activities to Google Fit
 */

const db = require('../db/database');

const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
const REDIRECT_URI = process.env.GOOGLE_REDIRECT_URI || 'http://localhost:3000/api/auth/google/callback';

/**
 * Get Google OAuth2 Authorization URL
 */
function getAuthUrl() {
  const scopes = [
    'https://www.googleapis.com/auth/fitness.activity.read',
    'https://www.googleapis.com/auth/fitness.activity.write',
    'https://www.googleapis.com/auth/fitness.body.read',
    'https://www.googleapis.com/auth/fitness.body.write',
    'https://www.googleapis.com/auth/fitness.location.read',
    'https://www.googleapis.com/auth/fitness.location.write',
    'profile',
    'email'
  ];
  
  const params = new URLSearchParams({
    client_id: GOOGLE_CLIENT_ID,
    redirect_uri: REDIRECT_URI,
    response_type: 'code',
    scope: scopes.join(' '),
    access_type: 'offline',
    prompt: 'consent'
  });
  
  return `https://accounts.google.com/o/oauth2/v2/auth?${params.toString()}`;
}

/**
 * Exchange authorization code for tokens
 */
async function exchangeCode(code) {
  const params = new URLSearchParams({
    code,
    client_id: GOOGLE_CLIENT_ID,
    client_secret: GOOGLE_CLIENT_SECRET,
    redirect_uri: REDIRECT_URI,
    grant_type: 'authorization_code'
  });

  const response = await fetch('https://oauth2.googleapis.com/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: params.toString()
  });

  if (!response.ok) {
    const err = await response.json();
    throw new Error(err.error_description || 'Failed to exchange Google code');
  }

  return await response.json();
}

/**
 * Refresh Google tokens if expired
 */
async function refreshTokens(userId) {
  const tokens = await db.getExternalTokens(userId, 'google_fit');
  if (!tokens || !tokens.refresh_token) throw new Error('No Google Fit refresh token available');

  const params = new URLSearchParams({
    client_id: GOOGLE_CLIENT_ID,
    client_secret: GOOGLE_CLIENT_SECRET,
    refresh_token: tokens.refresh_token,
    grant_type: 'refresh_token'
  });

  const response = await fetch('https://oauth2.googleapis.com/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: params.toString()
  });

  if (!response.ok) {
    throw new Error('Failed to refresh Google Fit tokens');
  }

  const data = await response.json();
  const newTokens = {
    ...tokens,
    access_token: data.access_token,
    expires_at: Math.floor(Date.now() / 1000) + data.expires_in
  };

  await db.saveExternalTokens(userId, 'google_fit', newTokens);
  return newTokens;
}

/**
 * Upload an activity session to Google Fit
 */
async function uploadActivity(userId, activity) {
  let tokens = await db.getExternalTokens(userId, 'google_fit');
  if (!tokens) return { success: false, error: 'Not connected to Google Fit' };

  // Check expiration (with 1-minute buffer)
  if (tokens.expires_at < (Date.now() / 1000) + 60) {
    tokens = await refreshTokens(userId);
  }

  const startTime = new Date(activity.route_start_time).getTime();
  const durationMs = activity.duration_min * 60 * 1000;
  const endTime = startTime + durationMs;
  const nanoStart = startTime * 1000000;
  const nanoEnd = endTime * 1000000;

  // Map Activity Type
  // 8 = Running, 7 = Walking, 1 = Biking
  let activityType = 8; 
  if (activity.activity_type === 'Walk') activityType = 7;
  else if (activity.activity_type === 'Ride') activityType = 1;

  const sessionId = `stractz_${activity.id}_${startTime}`;

  // 1. Create Session
  const sessionBody = {
    id: sessionId,
    name: activity.activity_name,
    description: `Generated by StrAct Z - ${activity.distance_km}km`,
    startTimeMillis: startTime,
    endTimeMillis: endTime,
    activityType: activityType,
    application: { name: 'StrAct Z', version: '1.50.0' }
  };

  await fetch(`https://www.googleapis.com/fitness/v1/users/me/sessions/${sessionId}`, {
    method: 'PUT',
    headers: {
      'Authorization': `Bearer ${tokens.access_token}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(sessionBody)
  });

  // 2. Insert DataSets (Distance, Speed, Steps, Heart Rate)
  const dataSources = [
    {
      type: 'com.google.distance.delta',
      dataType: 'com.google.distance.delta',
      values: [{ fpVal: activity.distance_km * 1000 }] // meters
    },
    {
      type: 'com.google.speed',
      dataType: 'com.google.speed',
      values: [{ fpVal: (activity.distance_km * 1000) / (activity.duration_min * 60) }] // m/s
    },
    {
      type: 'com.google.step_count.delta',
      dataType: 'com.google.step_count.delta',
      values: [{ intVal: Math.round(activity.distance_km * (activityType === 7 ? 1400 : 1250)) }] // estimated steps
    }
  ];

  for (const ds of dataSources) {
    const streamId = `raw:${ds.type}:me:StrActZ:${sessionId}`;
    
    // Create Data Source
    await fetch(`https://www.googleapis.com/fitness/v1/users/me/dataSources`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${tokens.access_token}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        dataStreamName: ds.type,
        type: 'raw',
        application: { name: 'StrAct Z' },
        dataType: { name: ds.dataType, field: [{ name: ds.type.split('.').pop(), format: ds.values[0].intVal !== undefined ? 'integer' : 'floatPoint' }] }
      })
    }).catch(() => {}); // Ignore if already exists

    // Patch Data Point
    const datasetId = `${nanoStart}-${nanoEnd}`;
    await fetch(`https://www.googleapis.com/fitness/v1/users/me/dataSources/${streamId}/datasets/${datasetId}`, {
      method: 'PATCH',
      headers: {
        'Authorization': `Bearer ${tokens.access_token}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        dataSourceId: streamId,
        minStartTimeNs: nanoStart,
        maxEndTimeNs: nanoEnd,
        point: [{
          startTimeNanos: nanoStart,
          endTimeNanos: nanoEnd,
          dataTypeName: ds.dataType,
          value: ds.values
        }]
      })
    });
  }

  return { success: true };
}

// ─── Caching Layer ──────────────────────────────────────────────────────────
const statsCache = new Map(); // userId -> { data, expires }
const CACHE_TTL_MS = 10 * 60 * 1000; // 10 minutes

async function getTodayStats(userId, forceRefresh = false) {
  if (!forceRefresh) {
    const cached = statsCache.get(userId);
    if (cached && cached.expires > Date.now()) {
      return cached.data;
    }
  }

  let tokens = await db.getExternalTokens(userId, 'google_fit');
  if (!tokens) throw new Error('Not connected to Google Fit');

  if (tokens.expires_at < (Date.now() / 1000) + 60) {
    tokens = await refreshTokens(userId);
  }

  const now = new Date();
  const startOfDay = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();
  const endTime = now.getTime();

  const aggregateBody = {
    aggregateBy: [{
      dataTypeName: 'com.google.step_count.delta'
    }],
    bucketByTime: { durationMillis: 86400000 },
    startTimeMillis: startOfDay,
    endTimeMillis: endTime
  };

  const response = await fetch('https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${tokens.access_token}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(aggregateBody)
  });

  if (!response.ok) {
    const err = await response.json();
    throw new Error(err.message || 'Failed to fetch Google Fit stats');
  }

  const data = await response.json();
  let totalSteps = 0;
  
  if (data.bucket && data.bucket[0] && data.bucket[0].dataset && data.bucket[0].dataset[0].point) {
    const points = data.bucket[0].dataset[0].point;
    totalSteps = points.reduce((sum, p) => sum + (p.value[0].intVal || 0), 0);
  }

  const result = {
    steps: totalSteps,
    lastUpdate: new Date().toISOString()
  };

  statsCache.set(userId, { data: result, expires: Date.now() + CACHE_TTL_MS });
  return result;
}

async function disconnect(userId) {
  try {
    const tokens = await db.getExternalTokens(userId, 'google_fit');
    if (tokens && (tokens.access_token || tokens.refresh_token)) {
      const token = tokens.refresh_token || tokens.access_token;
      await fetch(`https://oauth2.googleapis.com/revoke?token=${token}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' }
      });
    }
  } catch (err) {
    console.error('[Google Fit] Revoke failed:', err.message);
  } finally {
    await db.deleteExternalTokens(userId, 'google_fit');
  }
}

function clearCache(userId) {
  statsCache.delete(userId);
}

module.exports = {
  getAuthUrl,
  exchangeCode,
  refreshTokens,
  uploadActivity,
  getTodayStats,
  clearCache,
  disconnect
};
