/**
 * Google Fit Service - Sync activities to Google Fit
 */

const db = require('../db/database');

const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
const REDIRECT_URI = process.env.GOOGLE_REDIRECT_URI || 'http://localhost:3000/api/auth/google/callback';

/**
 * Get Google OAuth2 Authorization URL
 */
function getAuthUrl() {
  const scopes = [
    'https://www.googleapis.com/auth/fitness.activity.read',
    'https://www.googleapis.com/auth/fitness.activity.write',
    'https://www.googleapis.com/auth/fitness.body.read',
    'https://www.googleapis.com/auth/fitness.body.write',
    'https://www.googleapis.com/auth/fitness.location.read',
    'https://www.googleapis.com/auth/fitness.location.write',
    'profile',
    'email'
  ];
  
  const params = new URLSearchParams({
    client_id: GOOGLE_CLIENT_ID,
    redirect_uri: REDIRECT_URI,
    response_type: 'code',
    scope: scopes.join(' '),
    access_type: 'offline',
    prompt: 'consent'
  });
  
  return `https://accounts.google.com/o/oauth2/v2/auth?${params.toString()}`;
}

/**
 * Exchange authorization code for tokens
 */
async function exchangeCode(code) {
  const params = new URLSearchParams({
    code,
    client_id: GOOGLE_CLIENT_ID,
    client_secret: GOOGLE_CLIENT_SECRET,
    redirect_uri: REDIRECT_URI,
    grant_type: 'authorization_code'
  });

  const response = await fetch('https://oauth2.googleapis.com/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: params.toString()
  });

  if (!response.ok) {
    const err = await response.json();
    throw new Error(err.error_description || 'Failed to exchange Google code');
  }

  return await response.json();
}

/**
 * Refresh Google tokens if expired
 */
async function refreshTokens(userId) {
  const tokens = await db.getExternalTokens(userId, 'google_fit');
  if (!tokens || !tokens.refresh_token) throw new Error('No Google Fit refresh token available');

  const params = new URLSearchParams({
    client_id: GOOGLE_CLIENT_ID,
    client_secret: GOOGLE_CLIENT_SECRET,
    refresh_token: tokens.refresh_token,
    grant_type: 'refresh_token'
  });

  const response = await fetch('https://oauth2.googleapis.com/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: params.toString()
  });

  if (!response.ok) {
    throw new Error('Failed to refresh Google Fit tokens');
  }

  const data = await response.json();
  const newTokens = {
    ...tokens,
    access_token: data.access_token,
    expires_at: Math.floor(Date.now() / 1000) + data.expires_in
  };

  await db.saveExternalTokens(userId, 'google_fit', newTokens);
  return newTokens;
}

/**
 * Upload an activity session to Google Fit
 */
async function uploadActivity(userId, activity) {
  let tokens = await db.getExternalTokens(userId, 'google_fit');
  if (!tokens) return { success: false, error: 'Not connected to Google Fit' };

  // Check expiration (with 1-minute buffer)
  if (tokens.expires_at < (Date.now() / 1000) + 60) {
    tokens = await refreshTokens(userId);
  }

  const startTime = new Date(activity.route_start_time).getTime();
  const durationMs = activity.duration_min * 60 * 1000;
  const endTime = startTime + durationMs;
  const nanoStart = (BigInt(startTime) * 1000000n).toString();
  const nanoEnd = (BigInt(endTime) * 1000000n).toString();

  // Map Activity Type
  // 8 = Running, 7 = Walking, 1 = Biking
  let activityType = 8; 
  if (activity.activity_type === 'Walk') activityType = 7;
  else if (activity.activity_type === 'Ride') activityType = 1;

  const sessionId = `stractz_${activity.id}_${startTime}`;

  // 1. Create Session
  const sessionBody = {
    id: sessionId,
    name: activity.activity_name,
    description: `Generated by StrAct Z - ${activity.distance_km}km`,
    startTimeMillis: startTime,
    endTimeMillis: endTime,
    activityType: activityType,
    application: { name: 'StrAct Z', version: '1.50.60', packageName: 'com.stractz.sync' }
  };

  await fetch(`https://www.googleapis.com/fitness/v1/users/me/sessions/${sessionId}`, {
    method: 'PUT',
    headers: {
      'Authorization': `Bearer ${tokens.access_token}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(sessionBody)
  });

  // 2. Insert DataSets (Distance, Speed, Steps, Calories, Heart Rate)
  const dataSources = [
    {
      type: 'com.google.distance.delta',
      dataType: 'com.google.distance.delta',
      values: [{ fpVal: activity.distance_km * 1000 }] // meters
    },
    {
      type: 'com.google.speed',
      dataType: 'com.google.speed',
      values: [{ fpVal: (activity.distance_km * 1000) / (activity.duration_min * 60) }] // m/s
    },
    {
      type: 'com.google.step_count.delta',
      dataType: 'com.google.step_count.delta',
      values: [{ intVal: Math.round(activity.distance_km * (activityType === 7 ? 1400 : 1250)) }] // estimated steps
    },
    {
      type: 'com.google.calories.expended',
      dataType: 'com.google.calories.expended',
      values: [{ fpVal: activity.distance_km * (activityType === 1 ? 25 : 65) }] // rough estimate kcal
    }
  ];

  // Optional Heart Rate
  if (activity.heart_rate_enabled === 'true' || activity.avg_hr) {
    const avgHr = activity.avg_hr || 140;
    dataSources.push({
      type: 'com.google.heart_rate.bpm',
      dataType: 'com.google.heart_rate.bpm',
      values: [{ fpVal: parseFloat(avgHr) }]
    });
  }

  const getFieldName = (type) => {
    if (type.includes('step_count')) return 'steps';
    if (type.includes('distance')) return 'distance';
    if (type.includes('calories')) return 'calories';
    if (type.includes('heart_rate')) return 'bpm';
    return type.split('.').pop();
  };

  for (const ds of dataSources) {
    // 1. Create or Get Data Source (POST)
    const dsBody = {
      type: 'raw',
      application: { name: 'StrAct Z', packageName: 'com.stractz.sync' },
      dataType: { 
        name: ds.type,
        field: [{ name: getFieldName(ds.type), format: ds.values[0].intVal !== undefined ? 'integer' : 'floatPoint' }]
      },
      device: { manufacturer: 'StrActZ', model: 'VirtualTracker', type: 'phone', uid: 'manual' }
    };

    const dsResponse = await fetch(`https://www.googleapis.com/fitness/v1/users/me/dataSources`, {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${tokens.access_token}`, 'Content-Type': 'application/json' },
      body: JSON.stringify(dsBody)
    });

    let streamId;
    if (dsResponse.ok || dsResponse.status === 409) {
      const dsData = await dsResponse.json();
      streamId = dsData.dataStreamId;
    } else {
      const err = await dsResponse.json();
      console.error(`[Google Fit] Data source creation failed:`, err);
      continue;
    }

    // 2. Patch Data Point
    const datasetId = `${nanoStart}-${nanoEnd}`;
    console.log(`[Google Fit] Uploading to ${streamId}: ${datasetId}`);
    
    const patchResponse = await fetch(`https://www.googleapis.com/fitness/v1/users/me/dataSources/${streamId}/datasets/${datasetId}`, {
      method: 'PATCH',
      headers: { 'Authorization': `Bearer ${tokens.access_token}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        dataSourceId: streamId,
        minStartTimeNs: nanoStart,
        maxEndTimeNs: nanoEnd,
        point: [{
          startTimeNanos: nanoStart,
          endTimeNanos: nanoEnd,
          dataTypeName: ds.type,
          value: ds.values
        }]
      })
    });

    if (!patchResponse.ok) {
      const errText = await patchResponse.text();
      console.error(`[Google Fit] Patch failed for ${ds.type}:`, errText);
    }
  }

  const totalSteps = dataSources.find(ds => ds.type === 'com.google.step_count.delta')?.values[0].intVal || 0;
  return { success: true, steps: totalSteps };
}

// ─── Caching Layer ──────────────────────────────────────────────────────────
const statsCache = new Map(); // userId -> { data, expires }
const CACHE_TTL_MS = 10 * 60 * 1000; // 10 minutes

async function getTodayStats(userId, forceRefresh = false) {
  if (!forceRefresh) {
    const cached = statsCache.get(userId);
    if (cached && cached.expires > Date.now()) {
      return cached.data;
    }
  }

  let tokens = await db.getExternalTokens(userId, 'google_fit');
  if (!tokens) throw new Error('Not connected to Google Fit');

  if (tokens.expires_at < (Date.now() / 1000) + 60) {
    tokens = await refreshTokens(userId);
  }

  const now = new Date();
  // Ensure we get 00:00:00 in Asia/Ho_Chi_Minh regardless of server timezone
  const hanoiDateStr = now.toLocaleDateString('en-CA', { timeZone: 'Asia/Ho_Chi_Minh' }); 
  const startOfDay = new Date(`${hanoiDateStr}T00:00:00.000+07:00`).getTime();
  const endTime = now.getTime();

  // Query 1: Official/General Steps
  const officialBody = {
    aggregateBy: [{ dataTypeName: 'com.google.step_count.delta' }],
    bucketByTime: { durationMillis: (endTime - startOfDay) || 86400000 },
    startTimeMillis: startOfDay,
    endTimeMillis: endTime
  };

  // Query 2: Manual Sync Steps (Direct Dataset Query)
  const nanoStart = BigInt(startOfDay) * 1000000n;
  const nanoEnd = BigInt(endTime) * 1000000n;
  const datasetId = `${nanoStart}-${nanoEnd}`;
  
  // 1. Fetch all data sources to find our dynamic ID
  const listRes = await fetch(`https://www.googleapis.com/fitness/v1/users/me/dataSources`, {
    method: 'GET',
    headers: { 'Authorization': `Bearer ${tokens.access_token}` }
  });

  let allSources = [];
  if (listRes.ok) {
    const listData = await listRes.json();
    allSources = listData.dataSource ? listData.dataSource.map(ds => ds.dataStreamId) : [];
  }

  // 2. Discover our stream ID
  const manualStream = allSources.find(s => s.includes('com.google.step_count.delta') && s.includes('StrActZ') && s.startsWith('raw:')) || 'raw:com.google.step_count.delta:me:StrActZ:VirtualTracker:manual:stract-z-sync';

  // 3. Query both official and manual data
  const [officialRes, manualRes] = await Promise.all([
    fetch('https://www.googleapis.com/fitness/v1/users/me/dataset:aggregate', {
      method: 'POST',
      headers: { 'Authorization': `Bearer ${tokens.access_token}`, 'Content-Type': 'application/json' },
      body: JSON.stringify(officialBody)
    }),
    fetch(`https://www.googleapis.com/fitness/v1/users/me/dataSources/${manualStream}/datasets/${datasetId}`, {
      method: 'GET',
      headers: { 'Authorization': `Bearer ${tokens.access_token}` }
    })
  ]);

  let googleTotal = 0;
  let syncedSteps = 0;

  if (officialRes.ok) {
    const data = await officialRes.json();
    if (data.bucket && data.bucket[0] && data.bucket[0].dataset && data.bucket[0].dataset[0].point) {
      googleTotal = data.bucket[0].dataset[0].point.reduce((sum, p) => sum + (p.value[0].intVal || 0), 0);
    }
  }

  if (manualRes.ok) {
    const data = await manualRes.json();
    if (data.point && data.point.length > 0) {
      syncedSteps = data.point.reduce((sum, p) => {
        const val = p.value && p.value[0] ? (p.value[0].intVal || Math.round(p.value[0].fpVal || 0)) : 0;
        return sum + val;
      }, 0);
    }
  }

  // Queue Sync Logic:
  // Get all activities uploaded today from local DB to see what WE expect
  const localActs = await db.getActivitiesByDate(userId, hanoiDateStr);
  const uploadedToday = localActs.filter(a => a.upload_status === 'uploaded');
  const expectedSyncedSteps = uploadedToday.reduce((sum, a) => {
    const activityType = a.activity_type === 'Walk' ? 7 : (a.activity_type === 'Ride' ? 1 : 8);
    const estSteps = Math.round(a.distance_km * (activityType === 7 ? 1400 : 1250));
    return sum + estSteps;
  }, 0);

  // queueSteps is what we uploaded but Google Fit hasn't "seen" in the stream yet
  const queueSteps = Math.max(0, expectedSyncedSteps - syncedSteps);

  // Double-counting prevention logic:
  // isolatedDeviceSteps = Total from Google (which might be merged) - Our manual steps
  const isolatedDeviceSteps = Math.max(0, googleTotal - syncedSteps);

  const stats = {
    steps: isolatedDeviceSteps + syncedSteps,
    officialSteps: isolatedDeviceSteps,
    syncedSteps,
    queueSteps,
    lastSync: now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', hour12: false }),
    timestamp: now.getTime(),
    debug: {
      manualOk: manualRes.ok,
      manualStatus: manualRes.status,
      googleTotal,
      expectedSyncedSteps,
      manualStream
    }
  };

  console.log('[Google Fit Debug]', stats);

  statsCache.set(userId, { data: stats, expires: Date.now() + CACHE_TTL_MS });

  return stats;
}

async function disconnect(userId) {
  try {
    const tokens = await db.getExternalTokens(userId, 'google_fit');
    if (tokens && (tokens.access_token || tokens.refresh_token)) {
      const token = tokens.refresh_token || tokens.access_token;
      await fetch(`https://oauth2.googleapis.com/revoke?token=${token}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' }
      });
    }
  } catch (err) {
    console.error('[Google Fit] Revoke failed:', err.message);
  } finally {
    await db.deleteExternalTokens(userId, 'google_fit');
  }
}

function clearCache(userId) {
  statsCache.delete(userId);
}

module.exports = {
  getAuthUrl,
  exchangeCode,
  refreshTokens,
  uploadActivity,
  getTodayStats,
  clearCache,
  disconnect
};
